using System.Collections.Generic;
using UnityEngine;

namespace TrainSudoku.Game
{
    /// <summary>Plays <see cref="AudioCue"/>s. Generated by the <see cref="GameManager"/>; safe to call when absent.</summary>
    /// <remarks>
    /// It plays through a small pool of <see cref="AudioSource"/>s rather than one shared <c>PlayOneShot</c>, because a
    /// <c>PlayOneShot</c> voice has no handle: the only lever is <c>Stop()</c> on the source, which kills every cue at
    /// once. A pool gives each in-flight sound a handle, which is what makes both the transition cancel and looping
    /// cues possible.
    /// </remarks>
    [RequireComponent(typeof(AudioSource))]
    public sealed class AudioCuePlayer : MonoBehaviour
    {
        /// <summary>Voices for one-shots. Thirteen sources with the music is comfortable against the project's 32 real voices.</summary>
        private const int VoiceCount = 8;

        /// <summary>Long enough not to click, short enough not to read as a fade. A hard Stop mid-waveform pops.</summary>
        private const float CancelFade = 0.06f;

        private const float LoopFade = 0.25f;

        private static AudioCuePlayer _instance;

        [SerializeField] private AudioCueLibrary library;
        [SerializeField] private AudioSource source;

        private sealed class Voice
        {
            public AudioSource Source;
            public int StartedFrame;
            public bool Hold;
            public float Volume;
            public float FadeSeconds;
            public float FadeRemaining;
            public bool Fading;
        }

        private readonly List<Voice> _voices = new List<Voice>();
        private readonly Dictionary<AudioCue, AudioSource> _loops = new Dictionary<AudioCue, AudioSource>();

        public static AudioCuePlayer Create(Transform parent, AudioCueLibrary library)
        {
            var go = new GameObject("Audio");
            go.transform.SetParent(parent, false);
            var source = go.AddComponent<AudioSource>();
            source.playOnAwake = false;
            source.spatialBlend = 0f;
            var player = go.AddComponent<AudioCuePlayer>();
            player.library = library;
            player.source = source;
            return player;
        }

        /// <summary>
        /// Re-reads the library at launch, so a clip or a mixer group filled in later never needs the scene touched.
        /// The voices are built here rather than baked: they carry no authored state, so a scene from before the audio
        /// layer needs no re-bake to get them.
        /// </summary>
        public void Configure(AudioCueLibrary cues)
        {
            if (cues != null) library = cues;
            EnsureVoices();
            AudioMute.SetMixer(library != null ? library.Mixer : null,
                               library != null ? library.MasterVolumeParameter : null);
        }

        public static void Play(AudioCue cue)
        {
            // Haptics ride the same cue vocabulary, and fire whether or not the cue has a clip.
            Haptics.Play(cue);
            if (_instance == null) return;
            _instance.PlayCue(cue);
        }

        /// <summary>
        /// Fades out the one-shots a screen change should not carry with it. Loops are left alone — a transition stops
        /// whatever was making the sound instead.
        /// </summary>
        public static void CancelInFlight()
        {
            if (_instance == null) return;
            _instance.CancelVoices();
        }

        /// <summary>Starts a looping cue, or leaves a running one alone. Never fires a haptic: a loop must not buzz.</summary>
        public static void PlayLoop(AudioCue cue)
        {
            if (_instance == null) return;
            _instance.StartLoopVoice(cue);
        }

        /// <summary>Stops a looping cue. Idempotent — callers stop loops that were never started.</summary>
        public static void StopLoop(AudioCue cue)
        {
            if (_instance == null) return;
            _instance.StopLoopVoice(cue);
        }

        public static void SetLoopsPaused(bool paused)
        {
            if (_instance == null) return;
            _instance.PauseLoops(paused);
        }

        /// <summary>Bends a running loop's pitch — the erase hold rides its own progress ring up.</summary>
        public static void SetLoopPitch(AudioCue cue, float pitch)
        {
            if (_instance == null) return;
            if (_instance._loops.TryGetValue(cue, out var loop) && loop != null) loop.pitch = pitch;
        }

        private void PlayCue(AudioCue cue)
        {
            if (library == null || !library.TryGetClip(cue, out var clip, out var volume)) return;
            EnsureVoices();
            var voice = TakeVoice();
            if (voice == null) return;

            voice.Source.clip = clip;
            voice.Source.volume = volume;
            voice.Source.pitch = 1f;
            voice.Source.outputAudioMixerGroup = library.OutputFor(cue, false);
            voice.StartedFrame = Time.frameCount;
            voice.Hold = library.HoldsThroughTransition(cue);
            voice.Volume = volume;
            voice.Fading = false;
            voice.FadeRemaining = 0f;
            voice.Source.Play();
        }

        private void CancelVoices()
        {
            foreach (var voice in _voices)
            {
                if (voice.Source == null || !voice.Source.isPlaying) continue;
                if (voice.Hold) continue;

                // The click that caused this transition started this very frame: Signage.Button plays the cue and then
                // invokes the action that transitions, all in one frame. Cancelling it would eat the sound of the tap
                // the player just made. (If a button ever animates before navigating, this wants to become a short
                // grace window on unscaled time rather than a frame count.)
                if (voice.StartedFrame == Time.frameCount) continue;

                voice.Fading = true;
                voice.FadeSeconds = CancelFade;
                voice.FadeRemaining = CancelFade;
            }
        }

        private void StartLoopVoice(AudioCue cue)
        {
            if (library == null || !library.TryGetClip(cue, out var clip, out var volume)) return;
            if (_loops.TryGetValue(cue, out var existing) && existing != null)
            {
                if (!existing.isPlaying) existing.Play();
                return;
            }

            var go = new GameObject($"Loop {cue}");
            go.transform.SetParent(transform, false);
            var loop = go.AddComponent<AudioSource>();
            loop.playOnAwake = false;
            loop.spatialBlend = 0f;
            loop.loop = true;
            loop.clip = clip;
            loop.volume = volume;
            loop.outputAudioMixerGroup = library.OutputFor(cue, true);
            loop.Play();
            _loops[cue] = loop;
        }

        private void StopLoopVoice(AudioCue cue)
        {
            if (!_loops.TryGetValue(cue, out var loop)) return;
            _loops.Remove(cue);
            if (loop == null) return;
            StartCoroutine(FadeOutAndDestroy(loop));
        }

        private System.Collections.IEnumerator FadeOutAndDestroy(AudioSource loop)
        {
            var from = loop.volume;
            var remaining = LoopFade;
            while (remaining > 0f && loop != null)
            {
                remaining -= Time.unscaledDeltaTime;
                loop.volume = from * Mathf.Clamp01(remaining / LoopFade);
                yield return null;
            }

            if (loop != null) SceneObjects.Destroy(loop.gameObject);
        }

        private void PauseLoops(bool paused)
        {
            foreach (var loop in _loops.Values)
            {
                if (loop == null) continue;
                if (paused) loop.Pause();
                else loop.UnPause();
            }
        }

        private void EnsureVoices()
        {
            if (_voices.Count >= VoiceCount) return;

            // The baked source is the first voice rather than a spare: the scene already carries it, and leaving it
            // idle beside eight new ones would be a ninth source doing nothing.
            if (_voices.Count == 0 && source != null)
            {
                source.playOnAwake = false;
                source.spatialBlend = 0f;
                source.loop = false;
                _voices.Add(new Voice { Source = source });
            }

            while (_voices.Count < VoiceCount)
            {
                var voice = gameObject.AddComponent<AudioSource>();
                voice.playOnAwake = false;
                voice.spatialBlend = 0f;
                voice.loop = false;
                _voices.Add(new Voice { Source = voice });
            }
        }

        /// <summary>The first idle voice, else the oldest cancellable one. A held voice is never stolen.</summary>
        private Voice TakeVoice()
        {
            foreach (var voice in _voices)
                if (voice.Source != null && !voice.Source.isPlaying) return voice;

            Voice oldest = null;
            foreach (var voice in _voices)
            {
                if (voice.Source == null || voice.Hold) continue;
                if (oldest == null || voice.StartedFrame < oldest.StartedFrame) oldest = voice;
            }

            oldest?.Source.Stop();
            return oldest;
        }

        private void Update()
        {
            for (var i = 0; i < _voices.Count; i++)
            {
                var voice = _voices[i];
                if (!voice.Fading || voice.Source == null) continue;

                voice.FadeRemaining -= Time.unscaledDeltaTime;
                if (voice.FadeRemaining <= 0f)
                {
                    voice.Source.Stop();
                    voice.Source.volume = voice.Volume;
                    voice.Fading = false;
                    continue;
                }

                voice.Source.volume = voice.Volume * Mathf.Clamp01(voice.FadeRemaining / voice.FadeSeconds);
            }
        }

        private void OnEnable()
        {
            _instance = this;
            if (source == null) source = GetComponent<AudioSource>();
            Haptics.Prepare();
        }

        private void OnDisable()
        {
            if (_instance == this) _instance = null;
        }
    }
}
