using UnityEngine;

namespace TrainSudoku.Game
{
    /// <summary>Plays <see cref="AudioCue"/>s through one AudioSource. Generated by the <see cref="GameManager"/>; safe to call when absent.</summary>
    [RequireComponent(typeof(AudioSource))]
    public sealed class AudioCuePlayer : MonoBehaviour
    {
        private static AudioCuePlayer _instance;

        [SerializeField] private AudioCueLibrary library;
        [SerializeField] private AudioSource source;

        public static AudioCuePlayer Create(Transform parent, AudioCueLibrary library)
        {
            var go = new GameObject("Audio");
            go.transform.SetParent(parent, false);
            var source = go.AddComponent<AudioSource>();
            source.playOnAwake = false;
            source.spatialBlend = 0f;
            var player = go.AddComponent<AudioCuePlayer>();
            player.library = library;
            player.source = source;
            return player;
        }

        public static void Play(AudioCue cue)
        {
            // Haptics ride the same cue vocabulary, and fire whether or not the cue has a clip.
            Haptics.Play(cue);
            if (_instance == null || _instance.library == null || _instance.source == null) return;
            if (_instance.library.TryGetClip(cue, out var clip, out var volume))
                _instance.source.PlayOneShot(clip, volume);
        }

        private void OnEnable()
        {
            _instance = this;
            if (source == null) source = GetComponent<AudioSource>();
            Haptics.Prepare();
        }

        private void OnDisable()
        {
            if (_instance == this) _instance = null;
        }
    }
}
